import type { Metadata } from 'next'
import { Roboto, Roboto_Condensed } from 'next/font/google'
import '@/styles/normalize.css'
import 'swiper/css'
import './globals.scss'
import ReduxFormProvider from './providers/ReduxFormProvider'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import { CallBtn } from '@/components/CallBtn/CallBtn'
import Footer from '@/components/footer/Footer'

import { Header } from '@/components/header/Header'
import 'react-toastify/dist/ReactToastify.css'
import NavbarContextProvider from './context/NavbarContext/NavbarContextProvider'
import { NavbarControl } from '@/components/navbar-conrol/NavbarControl'
import clsx from 'clsx'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })
const robotoCondensat = Roboto_Condensed({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    variable: '--roboto-c',
})

export const metadata: Metadata = {
    title: 'MOVEYOURCAR',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ReduxFormProvider>
            <NavbarContextProvider>
                <html lang="en">
                    <body
                        className={clsx(
                            roboto.className,
                            robotoCondensat.variable
                        )}
                    >
                        <Header />
                        {children}
                        <Footer />
                        <ToastContainer />
                        <CallBtn />
                        <NavbarControl />
                    </body>
                </html>
            </NavbarContextProvider>
        </ReduxFormProvider>
    )
}
